-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
-- vim.api.nvim_create_autocmd({ "BufRead", "BufNewFile" }, {
--  pattern = "*.cj",
--  callback = function()
-- 设置缓冲区 filetype 和缩进
--    vim.bo.filetype = "Cangjie"
--    vim.bo.shiftwidth = 4
--    vim.bo.tabstop = 4
--   vim.bo.expandtab = true
--    vim.bo.autoindent = true
--    vim.bo.smartindent = false
--    vim.bo.cindent = false
--  end,
--  desc = "Set filetype for Cangjie files",
-- )
